# Generated by Django 3.0.3 on 2020-02-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='artist',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='fact',
            old_name='song_name',
            new_name='song',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artist_name',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='song',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='fact',
            name='message',
            field=models.TextField(),
        ),
    ]
