# Generated by Django 3.0.5 on 2020-04-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0004_auto_20200408_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='song',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
